### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by undavide** [fusepilot/babel-preset-extendscript#4]
Hi,
I'm currently unable to run this babel preset (macOS 10.13.3, node 8.10.0). I'm using a `npm` script like:
```
  "scripts": {
    "babel": "babel src/photoshop.js --presets extendscript"
  },
```
but the result (no matter what the content of photoshop.js is, even `var a = 0;` turns out as `TypeError: src/photoshop.js: Cannot read property 'start' of undefined`. The log file is as follows:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'babel' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prebabel', 'babel', 'postbabel' ]
5 info lifecycle ES6_TEST@1.0.0~prebabel: ES6_TEST@1.0.0
6 info lifecycle ES6_TEST@1.0.0~babel: ES6_TEST@1.0.0
7 verbose lifecycle ES6_TEST@1.0.0~babel: unsafe-perm in lifecycle true
8 verbose lifecycle ES6_TEST@1.0.0~babel: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/davidebarranca/Desktop/WEBPACK/node_modules/.bin:/Users/davidebarranca/.rbenv/shims:/usr/local/opt/openssl/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/TeX/texbin:/Users/davidebarranca/bin:/Applications/calibre.app/Contents/console.app/Contents/MacOS:/usr/local/Cellar/ruby/2.4.2_1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle ES6_TEST@1.0.0~babel: CWD: /Users/davidebarranca/Desktop/WEBPACK
10 silly lifecycle ES6_TEST@1.0.0~babel: Args: [ '-c', 'babel src/photoshop.js --presets extendscript' ]
11 silly lifecycle ES6_TEST@1.0.0~babel: Returned: code: 1  signal: null
12 info lifecycle ES6_TEST@1.0.0~babel: Failed to exec babel script
13 verbose stack Error: ES6_TEST@1.0.0 babel: `babel src/photoshop.js --presets extendscript`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ES6_TEST@1.0.0
15 verbose cwd /Users/davidebarranca/Desktop/WEBPACK
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "babel"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error ES6_TEST@1.0.0 babel: `babel src/photoshop.js --presets extendscript`
22 error Exit status 1
23 error Failed at the ES6_TEST@1.0.0 babel script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Do you have any idea why it fails? Thank you!

Davide

**Comment by fusepilot** [comment]
Hey,

Just gave it a go on my machine (10.13.3, 8.10.0 also) and it worked. Which version of `babel-cli` and `babel-preset-extendscript` are you using?

Here's the repo I just tested it with.  https://github.com/fusepilot/babel-preset-extendscript-issue-4

**Comment by undavide** [comment]
This is from my `package-lock.json`:

```
    "babel-cli": {
      "version": "6.26.0",
      "resolved": "https://registry.npmjs.org/babel-cli/-/babel-cli-6.26.0.tgz",
      "integrity": "sha1-UCq1SHTX24itALiHoGODzgPQAvE=",
      "dev": true,
      "requires": {
        "babel-core": "6.26.0",
        "babel-polyfill": "6.26.0",
        "babel-register": "6.26.0",
        "babel-runtime": "6.26.0",
        "chokidar": "1.7.0",
        "commander": "2.13.0",
        "convert-source-map": "1.5.1",
        "fs-readdir-recursive": "1.1.0",
        "glob": "7.1.2",
        "lodash": "4.17.5",
        "output-file-sync": "1.1.2",
        "path-is-absolute": "1.0.1",
        "slash": "1.0.0",
        "source-map": "0.5.7",
        "v8flags": "2.1.1"
      },
```
and
```
    "babel-preset-extendscript": {
      "version": "0.1.1",
      "resolved": "https://registry.npmjs.org/babel-preset-extendscript/-/babel-preset-extendscript-0.1.1.tgz",
      "integrity": "sha1-fXKijYltIHmLB3GozVgrusv4Edo=",
      "dev": true,
      "requires": {
        "babel-plugin-check-es2015-constants": "6.22.0",
        "babel-plugin-transform-es2015-arrow-functions": "6.22.0",
        "babel-plugin-transform-es2015-block-scoped-functions": "6.22.0",
        "babel-plugin-transform-es2015-block-scoping": "6.26.0",
        "babel-plugin-transform-es2015-classes": "6.24.1",
        "babel-plugin-transform-es2015-computed-properties": "6.24.1",
        "babel-plugin-transform-es2015-destructuring": "6.23.0",
        "babel-plugin-transform-es2015-duplicate-keys": "6.24.1",
        "babel-plugin-transform-es2015-for-of": "6.23.0",
        "babel-plugin-transform-es2015-function-name": "6.24.1",
        "babel-plugin-transform-es2015-literals": "6.22.0",
        "babel-plugin-transform-es2015-modules-amd": "6.24.1",
        "babel-plugin-transform-es2015-modules-commonjs": "6.26.0",
        "babel-plugin-transform-es2015-modules-systemjs": "6.24.1",
        "babel-plugin-transform-es2015-modules-umd": "6.24.1",
        "babel-plugin-transform-es2015-object-super": "6.24.1",
        "babel-plugin-transform-es2015-parameters": "6.24.1",
        "babel-plugin-transform-es2015-shorthand-properties": "6.24.1",
        "babel-plugin-transform-es2015-spread": "6.22.0",
        "babel-plugin-transform-es2015-sticky-regex": "6.24.1",
        "babel-plugin-transform-es2015-template-literals": "6.22.0",
        "babel-plugin-transform-es2015-typeof-symbol": "6.23.0",
        "babel-plugin-transform-es2015-unicode-regex": "6.24.1",
        "babel-plugin-transform-es3-property-literals": "6.22.0",
        "babel-plugin-transform-object-rest-spread": "6.26.0",
        "babel-plugin-transform-regenerator": "6.26.0",
        "babel-template": "6.26.0"
      }
    },
```
Thank you!

**Comment by fusepilot** [comment]
Hmm, looks like the same versions I'm running. Can you download the repo I linked earlier and run `npm install` and `npm run babel` in it and see what happens?

**Comment by undavide** [comment]
I've tested this, and you may help in figuring out what's wrong here. Your repo works flawlessly: I've moved everything I have in mine, and it then fails. Testing element after element, it turns out that the culprit is the `.babelrc` file that I have in the root.
The `.babelrc` is there because it was used by webpack. By the way the content was:

```
{
  "presets": ["extendscript"]
}
```
Even if `.babelrc` is empty, the process is going to fail! Do you have any idea why?

Fact is that, as far as I understand (I'm following a tutorial on Webpack, I'm still learning) I need that file...
Thank you!

**Comment by fusepilot** [comment]
Ah, yes. You can't use both babel-cli arguments and .babelrc simultaneously.

I'd recommend going the .babelrc route. So just remove `--presets extendscript` from your babel command and you should be good to go!
